command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "$DATABRICKS_APP_PORT"]
env:
  - name: API_KEY
    valueFrom: api-key-secret
resources:
  - name: api-key-secret
    secret:
      scope: "bi-nbcr-secrets"
      key: "api-key"
  - name: postgres
    postgres:
      branch: projects/db-bi-bnbo/branches/production
      database: projects/db-bi-bnbo/branches/production/databases/databricks-postgres
      permission: CAN_CONNECT_AND_CREATE
