command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "$DATABRICKS_APP_PORT"]
env:
  - name: API_KEY
    valueFrom:
      resourceName: api-key-secret
      resourceField: value
  - name: POSTGRES_USER
    valueFrom:
      resourceName: postgres
      resourceField: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      resourceName: postgres
      resourceField: password
  - name: POSTGRES_HOST
    valueFrom:
      resourceName: postgres
      resourceField: host
  - name: POSTGRES_PORT
    valueFrom:
      resourceName: postgres
      resourceField: port

resources:
  - name: api-key-secret
    secret:
      scope: bi-nbcr-secrets
      key: api-key
  - name: postgres
    postgres:
      branch: projects/db-bi-bnbo/branches/production
      database: projects/db-bi-bnbo/branches/production/databases/db-3s9f-s58q0wwfo3
      permission: CAN_CONNECT_AND_CREATE